sudo: required
services:
  - docker


before_install:
  - docker build -t taram/docker -f Dockerfile.dev .


script:
  - docker run taram/docker npm run test -- --coverage


group: deprecated-2017Q4

